### ISSUE TITLE
omni_drive_controller does not exist in noetic

### ISSUE THREAD

**Issue by argenos** [pal-robotics/omni_base_simulation#1]
After following the installation tutorials for the omni base, and trying to launch the simulation following [the next tutorial](http://wiki.ros.org/Robots/TIAGo-OMNI-base/Tutorials/Installation/OMNI_Base_Simulation), the terminal throws an error:

![image](https://user-images.githubusercontent.com/5426039/236173775-2a0230c3-d67a-4b08-a7f6-7eb532515bf7.png)

The tutorial does mention the controller is not publicly available (Although a bit too late in my opinion, I would have started with a different robot had I known this was untestable). Is there a way to test this before purchasing the robot?

**Comment by saikishor** [comment]
Hello @argenos,

First of all, thank you for showing interest in our Product and its simulation. Regarding your issue, yes the controller is not loaded as this is a proprietary software. However, it does load a gazebo plugin that does simulate the behavior of the real robot. In order to test it, you can publish the command to the `/mobile_base_controller/cmd_vel` and you should see the base moving and you also get the odometry published in a topic. We hope this helps you to test our simulation.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by argenos** [comment]
Understood! I'll give it a try in that case. Thanks for the fast reply!
